-- CREAMOS LA BASE DE DATOS LABORATORIO
CREATE DATABASE LABORATORIO;

-- USAMOS/SELECIONAMOS LA BASE DE DATOS PARA PODER CREAR LAS TABLAS 
USE LABORATORIO;
 
-- CREAMOS LA TABLA FACTURAS EN LA BASE DE DATOS
CREATE TABLE facturas (
	letra CHAR,
    numero INT,
    cliente_id INT,
    articulo_id INT,
    fecha DATE,
    monto DOUBLE,
    primary key(letra, numero)
);
 
-- CREAMOS LA TABLA ARTICULOS 
CREATE TABLE articulos (
	articulo_id INT PRIMARY KEY,
    nombre VARCHAR(50),
    precio DOUBLE,
    stock INT
); 

-- CREAMOS LA TABLA CLIENTES
CREATE TABLE clientes(
	cliente_id INT PRIMARY KEY,
    nombre VARCHAR(25),
    apellido VARCHAR(25),
    cuit CHAR(16),
    direccion VARCHAR(50),
    comentarios VARCHAR(50)
);

# SHOW TABLES;

-- MODIFICAMOS LA TABLA FACTURAS
ALTER TABLE facturas 
	CHANGE cliente_id IDCliente INT,
    CHANGE articulo_id IDArticulo INT,
    MODIFY monto DOUBLE unsigned;

-- MODIFICAMOS LA TABLA ARTICULOS
ALTER TABLE articulos
	CHANGE articulo_id IDArticulo INT,
    MODIFY nombre VARCHAR(75),
    MODIFY precio DOUBLE UNSIGNED NOT NULL,
    MODIFY stock INT UNSIGNED NOT NULL;
    
-- MODIFICAMOS LA TABLA CLIENTES
ALTER TABLE clientes 
	CHANGE cliente_id IDCliente INT,
    MODIFY nombre VARCHAR(30) NOT NULL,
    MODIFY apellido VARCHAR(35) NOT NULL,
    CHANGE comentarios observaciones VARCHAR(255);


-- INSERTAMOS DATOS EN LA TABLA FACTURAS
INSERT INTO facturas (`letra`,`numero`, `IDCliente`,`IDArticulo`, `fecha`,`monto`)
			VALUES	 ('A', 28, 14, 335, "2021-03-18", 1589.50);
            
INSERT INTO facturas (`letra`,`numero`, `IDCliente`,`IDArticulo`, `fecha`,`monto`)
			VALUES	 ('A', 39, 26, 157, "2021-04-12", 979.75);
            
INSERT INTO facturas (`letra`,`numero`, `IDCliente`,`IDArticulo`, `fecha`,`monto`)
			VALUES	 ('B', 8, 17, 95, "2021-04-25", 513.35);
            
INSERT INTO facturas (`letra`,`numero`, `IDCliente`,`IDArticulo`, `fecha`,`monto`)
			VALUES	 ('B', 12, 5, 441, "2021-05-03",  2385.70);
            
INSERT INTO facturas (`letra`,`numero`, `IDCliente`,`IDArticulo`, `fecha`,`monto`)
			VALUES	 ('B', 19, 50, 157, "2021-05-26", 979.75);
            
-- MOSTRAMOS LOS DATOS INGRESADOS
# SELECT  * FROM facturas;

-- INSERTAMOS DATOS EN LA TABLA DE ARTICULOS
INSERT INTO  articulos (`IDArticulo`, `nombre`, `precio`, `stock`)
			VALUES (95, "Webcam con Micrófono Plug & Play", 513.35, 39);
            
INSERT INTO  articulos (`IDArticulo`, `nombre`, `precio`, `stock`)
			VALUES (157, "Apple AirPods Pro", 979.75, 152);
            
INSERT INTO  articulos (`IDArticulo`, `nombre`, `precio`, `stock`)
			VALUES ( 335, "Lavasecarropas Automático Samsung", 1589.50, 12);

INSERT INTO  articulos (`IDArticulo`, `nombre`, `precio`, `stock`)
			VALUES (411, "Gloria Trevi / Gloria / CD+DVD", 2385.70, 2);

-- MOSTRAMOS LOS DATOS INSERTAMODS
#SELECT * FROM articulos;

-- INSERTAMOS DATOS EN LA TABLA CLIENTES
INSERT INTO clientes (`IDCliente`, `nombre`, `apellido`, `cuit`, `direccion`, `observaciones`)
VALUES 				 (5, "Santiago", "González", "23-24582359-9", "Uriburu 558 - 7ºA", "VIP");

INSERT INTO clientes (`IDCliente`, `nombre`, `apellido`, `cuit`, `direccion`, `observaciones`)
VALUES 				 (14, "Gloria", "Fernández", "23-35965852-5", "Constitución 323", "GBA");

INSERT INTO clientes (`IDCliente`, `nombre`, `apellido`, `cuit`, `direccion`, `observaciones`)
VALUES 				 (17, "Gonzalo", "López", "23-33587416-0", "Arias 2624", "GBA");

INSERT INTO clientes (`IDCliente`, `nombre`, `apellido`, `cuit`, `direccion`, `observaciones`)
VALUES 				 (26, "Carlos", "García", "23-42321230-9", "Pasteur 322 -2ºC", "VIP");

INSERT INTO clientes (`IDCliente`, `nombre`, `apellido`, `cuit`, `direccion`, `observaciones`)
VALUES 				 (50, "Micaela", "Altieri", "23-22885566-5", "Santamarina 1255", "GBA");

-- MOSTRAMOS LOS DATOS 
#SELECT * FROM clientes;

-- VEMOS LA ESTRUCTURA DE LA TABLA IMPORTADA
# DESC CLIENTES_NEPTUNO;

-- MODIFCAMOS LA ESTRUCTURA
ALTER TABLE CLIENTES_NEPTUNO
	MODIFY IDCliente VARCHAR(5) PRIMARY KEY,
    MODIFY NombreCompania VARCHAR(100) NOT NULL,
    MODIFY Pais VARCHAR(15) NOT NULL;
    
-- MODIFICAMOS EL NOMBRE DE LA TABLA CLIENTES POR CONTACTOS
ALTER TABLE CLIENTES RENAME CONTACTOS;

-- MODIFCAMOS LA ESTRUCTURA DE LA TABLA IMPORTADA (CLIENTES)
ALTER TABLE CLIENTES
	MODIFY Cod_Cliente VARCHAR(7) PRIMARY KEY,
    MODIFY Empresa VARCHAR(100) NOT NULL,
    MODIFY Ciudad VARCHAR(25) NOT NULL,
    MODIFY Telefono INT UNSIGNED,
    MODIFY Responsable VARCHAR(30);

-- MODIFCAMOS LA ESTRUCTURA DE LA TABLA IMPORTADA (PEDIDOS)
ALTER TABLE PEDIDOS
	MODIFY Numero_Pedido INT PRIMARY KEY,
    MODIFY Codigo_Cliente VARCHAR(7) NOT NULL,
    MODIFY Fecha_Pedido DATE NOT NULL,
    MODIFY Forma_Pago ENUM('CONTADO', 'APLAZADO', 'TARJETA'),
	MODIFY Enviado ENUM ('SI', 'NO');

-- MODIFCAMOS LA ESTRUCTURA DE LA TABLA IMPORTADA (PRODUCTOS)
ALTER TABLE PRODUCTOS
	MODIFY COD_PRODUCTO INT UNSIGNED PRIMARY KEY,
	MODIFY SECCION VARCHAR(20) NOT NULL,
	MODIFY NOMBRE VARCHAR(40) NOT NULL,
	MODIFY IMPORTADO ENUM('VERDADERO', 'FALSO') NOT NULL,
	MODIFY ORIGEN VARCHAR(25) NOT NULL,
	MODIFY DIA INT UNSIGNED NOT NULL,
	MODIFY MES INT UNSIGNED NOT NULL,
	MODIFY ANO INT UNSIGNED NOT NULL;

-- MOSTRAMOS LOS DATOS DE CLIENTES_NEPTUNO
SELECT * FROM CLIENTES_NEPTUNO;
SELECT NombreCompania, Ciudad, Pais FROM CLIENTES_NEPTUNO;
SELECT NombreCompania, Ciudad, Pais FROM CLIENTES_NEPTUNO ORDER BY Pais;
SELECT NombreCompania, Ciudad, Pais FROM CLIENTES_NEPTUNO ORDER BY Pais, Ciudad;
SELECT NombreCompania, Ciudad, Pais FROM CLIENTES_NEPTUNO ORDER BY Pais, Ciudad LIMIT 10;
SELECT NombreCompania, Ciudad, Pais FROM CLIENTES_NEPTUNO ORDER BY Pais, Ciudad LIMIT 5 OFFSET 10;
SELECT * FROM CLIENTES_NEPTUNO WHERE Pais = 'ARGENTINA';
SELECT * FROM CLIENTES_NEPTUNO WHERE Pais <> 'ARGENTINA' ORDER BY Pais;
SELECT * FROM CLIENTES_NEPTUNO WHERE Pais = 'ARGENTINA' OR Pais = 'VENEZUELA' OR Pais = 'BRASIL' ORDER BY Pais, Ciudad;
SELECT * FROM CLIENTES_NEPTUNO WHERE IDCLIENTE LIKE 'C%';
SELECT * FROM CLIENTES_NEPTUNO WHERE Ciudad LIKE 'B____';

-- MOSTRAMOS LOS DATOS DE LA TABLA NACIMIENTOS
SELECT * FROM NACIMIENTOS WHERE Nacionalidad = 'EXTRANJERA';
SELECT * FROM NACIMIENTOS WHERE Edad_Madre < 18 ORDER BY Edad_Madre;
SELECT * FROM NACIMIENTOS WHERE Edad_Madre = Edad_Padre;
SELECT * FROM NACIMIENTOS WHERE Edad_Padre-Edad_Madre > 40;
SELECT * FROM NACIMIENTOS WHERE Semanas < 20 ORDER BY Semanas DESC;
SELECT * FROM NACIMIENTOS WHERE Sexo = 'FEMENINO' AND Nacionalidad = 'EXTRANJERA' AND Estado_Civil_Madre = 'SOLTERA' AND Edad_Madre > 40;
SELECT * FROM NACIMIENTOS WHERE Semanas BETWEEN 20 AND 25 ORDER BY Semanas;
SELECT * FROM NACIMIENTOS WHERE Comuna IN (1101, 3201, 5605, 8108, 9204, 13120, 15202) ORDER BY Comuna;
SELECT * FROM NACIMIENTOS WHERE Hijos_Total > 10;

-- DROPEAMOS LA BASE DE DATOS PARA IMPORTAR BACKUP
DROP DATABASE LABORATORIO;

-- MOSTRAMOS DATOS DE LA TABLA CLIENTES_NEPTUNO (CONCAT)
SELECT IDCliente, NombreCompania, CONCAT(Direccion, ' - ',  Ciudad, ' - ', Pais) UBICACION FROM CLIENTES_NEPTUNO;
SELECT IDCliente, NombreCompania, CONCAT_WS(  ' - ', Direccion , Ciudad,  Pais) UBICACION FROM CLIENTES_NEPTUNO;
SELECT IDCliente, UPPER(NombreCompania) EMPRESA, CONCAT_WS(  ' - ', Direccion , Ciudad,  Pais) UBICACION FROM CLIENTES_NEPTUNO;
SELECT LOWER(IDCliente) CODIGO, UPPER(NombreCompania) EMPRESA, CONCAT_WS(  ' - ', Direccion , Ciudad,  Pais) UBICACION FROM CLIENTES_NEPTUNO;
SELECT *, UPPER(CONCAT(LEFT(Ciudad, 1), LEFT(Pais, 1), RIGHT(Pais, 2))) AS CODIGO FROM CLIENTES_NEPTUNO;

-- MOSTRAMOS DATOS DE LA TABLA NACIMIENTOS (FUNCIONES NUEVAS)
SELECT Fecha, LEFT(Sexo, 1) AS SEXO, LEFT(Tipo_Parto, 1) AS TIPO FROM NACIMIENTOS;
SELECT Sexo, Fecha, Tipo_Parto, Atenc_Part, Local_Part, SUBSTRING(Fecha, 4, 2) AS MES FROM NACIMIENTOS ORDER BY MES;
SELECT Sexo, Fecha, Tipo_Parto, REPLACE(Nacionalidad, 'Chilena', 'Ciudadana') AS NACIONALIDAD FROM NACIMIENTOS;
SELECT Sexo, COUNT(Sexo) AS NACIMIENTOS FROM NACIMIENTOS GROUP BY Sexo;

-- MOSTRAMOS DATOS DE LA TABLA PEDIDOS_NEPTUNO (FUNCIONES DATE)
SELECT * FROM PEDIDOS_NEPTUNO WHERE YEAR(FechaPedido) = 1998;
SELECT * FROM PEDIDOS_NEPTUNO WHERE MONTH(FechaPedido) BETWEEN 8 AND 9 AND YEAR(FechaPedido) = 1997;
SELECT * FROM PEDIDOS_NEPTUNO WHERE DAY(FechaPedido) = 1;
SELECT *, DATEDIFF(CURDATE(), FechaPedido)  'DIAS TRANSCURRIDOS' FROM PEDIDOS_NEPTUNO;
SELECT *, DATEDIFF(CURDATE(), FechaPedido)  'DIAS TRANSCURRIDOS', DAYNAME(FechaPedido) DIA FROM PEDIDOS_NEPTUNO;
SELECT *, DATEDIFF(CURDATE(), FechaPedido)  'DIAS TRANSCURRIDOS', DAYNAME(FechaPedido) DIA, DAYOFYEAR(FechaPedido)  'DIA DEL AÑO' FROM PEDIDOS_NEPTUNO;
SELECT *, DATEDIFF(CURDATE(), FechaPedido)  'DIAS TRANSCURRIDOS', DAYNAME(FechaPedido) DIA, DAYOFYEAR(FechaPedido)  'DIA DEL AÑO', MONTHNAME(FechaPedido)  'MES' FROM PEDIDOS_NEPTUNO;
SELECT *, DATEDIFF(CURDATE(), FechaPedido)  'DIAS TRANSCURRIDOS', DAYNAME(FechaPedido) DIA, DAYOFYEAR(FechaPedido)  'DIA DEL AÑO', MONTHNAME(FechaPedido)  'MES', ADDDATE(FechaPedido, INTERVAL 30 DAY)  'PRIMER VENCIMIENTO' FROM PEDIDOS_NEPTUNO;
SELECT *, DATEDIFF(CURDATE(), FechaPedido)  'DIAS TRANSCURRIDOS', DAYNAME(FechaPedido) DIA, DAYOFYEAR(FechaPedido)  'DIA DEL AÑO', MONTHNAME(FechaPedido)  'MES', ADDDATE(FechaPedido, INTERVAL 30 DAY)  'PRIMER VENCIMIENTO', ADDDATE(FechaPedido, INTERVAL 2 MONTH)  'SEGUNDO VENCIMIENTO' FROM PEDIDOS_NEPTUNO;

SELECT *, ROUND(Cargo * 0.21, 2) IVA FROM PEDIDOS_NEPTUNO;
SELECT *, ROUND(Cargo * 0.21, 2) IVA, ROUND(Cargo * 1.21, 2) NETO FROM PEDIDOS_NEPTUNO;
SELECT *, ROUND(Cargo * 0.21, 2) IVA, ROUND(Cargo * 1.21, 2) NETO, FLOOR(ROUND(Cargo * 1.21, 2)) 'REDONDEO A FAVOR CLIENTE' FROM PEDIDOS_NEPTUNO;
SELECT *, ROUND(Cargo * 0.21, 2) IVA, ROUND(Cargo * 1.21, 2) NETO, FLOOR(ROUND(Cargo * 1.21, 2)) 'REDONDEO A FAVOR CLIENTE', CEIL(ROUND(Cargo * 1.21, 2)) 'REDONDEO A FAVOR EMPRESA' FROM PEDIDOS_NEPTUNO;

SELECT COUNT(*) FROM PEDIDOS_NEPTUNO;
SELECT COUNT(Transportista) 'ENTREGAS SPEEDY EXPRESS' FROM PEDIDOS_NEPTUNO WHERE Transportista = 'SPEEDY EXPRESS';
SELECT COUNT(Empleado) VENTAS FROM PEDIDOS_NEPTUNO WHERE Empleado LIKE 'C%';
SELECT Transportista, COUNT(IdPedido) AS ENTREGAS FROM PEDIDOS_NEPTUNO GROUP BY Transportista;
SELECT NombreCompania CLIENTE, ROUND(SUM(Cargo), 2) 'TOTAL GASTOS' FROM PEDIDOS_NEPTUNO GROUP BY CLIENTE;
SELECT YEAR(FechaPedido) AÑO, MONTHNAME(FechaPedido) MES, COUNT(IdPedido) VENTAS FROM PEDIDOS_NEPTUNO GROUP BY AÑO, MES ORDER BY AÑO, MONTH(FECHAPEDIDO);
SELECT Empleado, ROUND(SUM(Cargo), 2) FACTURACION, ROUND(AVG(Cargo), 2) PROMEDIO, MAX(Cargo) 'MEJOR VENTA', MIN(Cargo) 'PEOR VENTA', COUNT(Cargo) AS VENTAS FROM PEDIDOS_NEPTUNO GROUP BY Empleado;

-- MOSTRAMOS DATOS DE LA TABLA PRODUCTOS_NEPTUNO
SELECT ROUND(AVG(PrecioUnidad), 2) 'PRECIO PROMEDIO' FROM PRODUCTOS_NEPTUNO;
SELECT ROUND(AVG(PrecioUnidad), 2) 'PRECIO PROMEDIO', MIN(PrecioUnidad) 'PRECIO MINIMO' FROM PRODUCTOS_NEPTUNO;
SELECT ROUND(AVG(PrecioUnidad), 2) 'PRECIO PROMEDIO', MIN(PrecioUnidad) 'PRECIO MINIMO', MAX(PrecioUnidad) 'PRECIO MAXIMO' FROM PRODUCTOS_NEPTUNO;
SELECT NombreCategoria AS CATEGORIA, MAX(PrecioUnidad) AS 'PRECIO MAXIMO' FROM PRODUCTOS_NEPTUNO GROUP BY CATEGORIA;


-- MOSTRAMOS DATOS DE LA TABLA PRODUCTOS
SELECT Seccion, COUNT(Seccion) CANTIDAD FROM PRODUCTOS GROUP BY Seccion ORDER BY CANTIDAD DESC;
 
